var array_of_fake_names =   ["Ambrose Green",
			"Rebecca Ray" ,
			"Carry Gibson" ,
			"Antonia Toke" ,
			"Abbey Fowler" ,
			"Margaux Knight" ,
			"Ami Dennis" ,
			"Dreda Gilman" ,
			"Buster Reamer" ,
			"Cedric Zimmer" ,
			"Chryssa Friedline" ,
			"Humbert Rega" ,
			"Brianna Mortland" ,
			"September Kava" ,
			"Eunice Mcloskey" ,
			"Louisa Poley" ,
			"Maxwell Maclagan" ,
			"Rudy Young" ,
			"Shavonne Eckhardstein" ,
			"Lydia Fraser" ,
			"Anderson Finck" ,
			"Elizabeth Hiles" ,
			"Vikki Hawkins" ,
			"Clinton Van" ,
			"Cary Smith" ,
			"Tansy Hills" ,
			"Evangelina Smail" ,
			"Reagan Whittier" ,
			"Isolda Whitten" ,
			"Ginette Coveney" ,
			"Panda Geyer" ,
			"Paul Kepplinger" ,
			"Ronnie Basinger" ,
			"Pip Grant" ,
			"Chelsea Henderson" ,
			"Montana Eve" ,
			"Kathi Cross" ,
			"Fortune Teagarden" ,
			"Emma Yates" ,
			"Darren Guess" ,
			"Ferdinanda Jube" ,
			"Topsy Law" ,
			"Jodi Townsend" ,
			"Laverne Pritchard" ,
			"Lyndon Northey" ,
			"Bob Larson" ,
			"Katrina Donkin" ,
			"Trecia Kemble" ,
			"Forest Stone" ,
			"Stu Field" ,
			"Donalda Patton" ,
			"Kenith Cressman" ,
			"Magdalen Wire" ,
			"Jonquil Berkheimer" ,
			"Barrett Greene" ,
			"Kolby Park" ,
			"Ferdy Prevatt" ,
			"Russ Williamson" ,
			"Emmerson Cable" ,
			"Asia Gertraht" ,
			"Randy Patterson" ,
			"Julian Mcmichaels" ,
			"Joan Scott" ,
			"Mayson Eisenhart" ,
			"Barney Smith" ,
			"Ermintrude Harshman" ,
			"Cassie Turzanski" ,
			"Sally Buttermore" ,
			"Bindy Leslie" ,
			"Royal Candles" ,
			"Claribel Griffis" ,
			"Reed Johnston" ,
			"Brandi Adams" ,
			"Delma Jackson" ,
			"Sunshine Bellinger" ,
			"Godiva Wilo" ,
			"Marquise Poorbaugh" ,
			"Orville Roberts" ,
			"Merrill Harrold" ,
			"Kyla Pheleps" ,
			"Edweena Werner" ,
			"Tristram Owens" ,
			"Robyn Mueller" ,
			"Kiley Lucy" ,
			"Heaven Keilbach" ,
			"Rosannah Keppel" ,
			"Emmie Garneys" ,
			"Herbert Burris" ,
			"Antwan Prechtl" ,
			"Rocky Treeby" ,
			"Nowell Shaner" ,
			"Lyn Jowers" ,
			"Isa Fiscina" ,
			"Orson Woollard" ,
			"Theodora Merryman" ,
			"Sybil Clewett" ,
			"Mona Wickes" ,
			"Lorn Mccrady" ,
			"Jerald Zeal" ,
			"Samuel Pierce" ,
			"Jacinth Hay" ,
			"Carmen Fry" ,
			"Anne Tireman" ,
			"Coleman Fuller" ,
			"Tex Warner" ,
			"Githa Faast" ,
			"Mae Rice" ,
			"Booker Sanforth" ,
			"Jasmin Breitenstein" ,
			"Vera Baldwin" ,
			"Nigel Bridger" ,
			"Rose Waldron" ,
			"Orrell Soames" ,
			"Debbie Drumm" ,
			"Benedicta Jackson" ,
			"Lyndsey Ironmonger" ,
			"Georgene Atkinson" ,
			"Laetitia Garry" ,
			"Leesa Schaeffer" ,
			"Innocent Schreckengost" ,
			"Crawford Rose" ,
			"Major Lafortune" ,
			"Beryl Mackendoerfer" ,
			"Kenneth Ludwig" ,
			"Leone Wells" ,
			"Braden Ramos" ,
			"Alanna Weinstein" ,
			"Juliet Laurence" ,
			"Etta Blunt" ,
			"Kam Roby" ,
			"Hunter Todd" ,
			"Adolph Rawls" ,
			"Harding Olphert" ,
			"Margo Crom" ,
			"Harve Conkle" ,
			"Carlisa Houston" ,
			"Jayden Ling" ,
			"Grant Kadel" ,
			"Philbert Christopher" ,
			"Caren Mccallum" ,
			"Lucian Barrett" ,
			"Gregory Weeter" ,
			"Sharla Hoopengarner" ,
			"Lanford Elder" ,
			"Bertram Sandford" ,
			"Marshal Newton" ,
			"Janeka Cox" ,
			"Helen Thompson" ,
			"Benjamin Basmanoff" ,
			"Angela Harris" ,
			"Arlene Whirlow" ,
			"Duke Bollinger" ,
			"Emmett Randolph" ,
			"Romy Richards" ,
			"Tami Kline" ,
			"Glenna Wynne" ,
			"Kirby Poehl" ,
			"Draven Biery" ,
			"Janelle Staymates" ,
			"Noble Reddish" ,
			"Christabel Light" ,
			"Kerensa Schuth" ,
			"Palmer Butterfill" ,
			"Silvia Diller" ,
			"Regan Rockwell" ,
			"Trevelyan Leach" ,
			"Terry Ruhl" ,
			"Candis Compton" ,
			"Harriett Ritter" ,
			"Silas Carr" ,
			"Carmella Mills" ,
			"Elsie Metzer" ,
			"Kelsey Felbrigge" ,
			"Clay Durstine" ,
			"Lori Agg" ,
			"Astor Pyle" ,
			"Haylie Churchill" ,
			"Kassidy Arthur" ,
			"Alison Gist" ,
			"Doug Pinney" ,
			"Seraphina Monahan" ,
			"Darden Littlefield" ,
			"Eva Whitling" ,
			"Gilbert Mang" ,
			"Darnell Mosser" ,
			"Ellis Giesler" ,
			"Azalea Rohtin" ,
			"Roswell Lord" ,
			"Mckenzie Linton" ,
			"Stefanie Mcdonald" ,
			"Ottoline Coates" ,
			"Desmond Steiner" ,
			"Mabelle Giesen" ,
			"India Raybould" ,
			"Garrett Mccune" ,
			"Mo Bagley" ,
			"Greer Finlay" ,
			"Trinity Rhodes" ,
			"Gussie Vorrasi" ,
			"Zackery Erschoff" ,
			"Nicodemus Bickerson" ,
			"Margery Quirin" ,
			"Shanene Ehret" ,
			"Sydney Margaret" ,
			"Melinda Hall" ,
			"Lawanda Wible" ,
			"Calista Elinor" ,
			"Kristel Crissman" ,
			"Midge Welty" ,
			"Rollo Buck" ,
			"Jayda Sheets" ,
			"Hayleigh Hayhurst" ,
			"Bettye Hall" ,
			"Gene Harrow" ,
			"Esmaralda Todd" ,
			"Dora Anderson" ,
			"Osbourne Pery" ,
			"Mariel Brinigh" ,
			"Warner Pickering" ,
			"Tabitha Fiddler" ,
			"Barrie Sidower" ,
			"Laila Pearsall" ,
			"Ethel Davis" ,
			"Ernestine Mercer" ,
			"Gaila Wheeler" ,
			"Jessica Gettemy" ,
			"Caitlyn Pearson" ,
			"Jordon Huey" ,
			"Noelle Snyder" ,
			"Cyrilla Philips" ,
			"Jodene Hincken" ,
			"Annabelle Orner" ,
			"Jocelin Franks" ,
			"Lennie Young" ,
			"Cherry Hujsak" ,
			"Davin Aultman" ,
			"Kimberlee Garland" ,
			"Jackie Straub" ,
			"Tamsen Wall" ,
			"Davis Congdon" ,
			"Kiefer Atweeke" ,
			"Milton Jenner" ,
			"Gladwin Pullman" ,
			"Johnny Robinson" ,
			"Leanora Parrish" ,
			"Christal Hooker" ,
			"Rosalyn Echard" ,
			"Rosalind Sandblom" ,
			"Jade Omara" ,
			"Emmy Wardle" ,
			"Cherilyn Cram" ,
			"Allannah Read" ,
			"Terence Lambert" ,
			"Keysha Bonner" ,
			"Brack Osteen" ,
			"Myranda Isemann" ,
			"Celeste Hatherly" ,
			"Tess Kern" ,
			"Aaliyah Vinsant" ,
			"Fox Siegrist" ,
			"Kyleigh Neely" ,
			"Barnabas Wile" ,
			"Meghan Trout" ,
			"Ambrosine Romanoff" ,
			"Kendall King" ,
			"Lucky Agg" ,
			"Sheard Zalack" ,
			"Joanne Herrold" ,
			"Wymond Murray" ,
			"Maddison Tillson" ,
			"Davida Ammons" ,
			"Nena Birdsall" ,
			"Marcia Hozier" ,
			"Millicent Haverrman" ,
			"Buck James" ,
			"Alanis Batten" ,
			"Trixie Blaine" ,
			"Albertina Gibson" ,
			"Tracie Wiggins" ,
			"Jake Christman" ,
			"Gwen Ballou" ,
			"Leigh Faqua" ,
			"Precious Driggers" ,
			"Floella Appleby" ,
			"Macie Fox" ,
			"Jeanie Costello" ,
			"Deangelo Harper" ,
			"Sloane Beedell" ,
			"Weldon Haynes" ,
			"Tania Ward" ,
			"Yashmine Boyd" ,
			"Cherish Wolfe" ,
			"Raymund Bennett" ,
			"Jeb Callison" ,
			"Joselyn Patterson" ,
			"Elisabeth Hays" ,
			"Bobbie Thigpen" ,
			"Eglantine Style" ,
			"Louiza Powers" ,
			"Dolph Eckert" ,
			"Gloria Blyant" ,
			"Lucinda Earhart" ,
			"Esta Tomco" ,
			"Carrie Burnett" ,
			"Sage Tennant" ,
			"Kolleen Kanaga" ,
			"Annalisa Oppenheimer" ,
			"Trev Nicola" ,
			"Lorrin Curry" ,
			"Phemie Hughes" ,
			"Jane Hanseu" ,
			"Halle Mathews" ,
			"Staci Hegarty" ,
			"Hartley Pennington" ,
			"Flora Courtney" ,
			"Myrtle Altmann" ,
			"Flo Tripp" ,
			"Katelyn Nabholz" ,
			"Emmet Dickinson" ,
			"Avice Bruxner" ,
			"Lennard Wheeler" ,
			"Royce Fryer" ,
			"Harland Weingarten" ,
			"Emory Llora" ,
			"Matthias Bastion" ,
			"Kerry Errett" ,
			"Princess Stephenson" ,
			"Bessie Mcintosh" ,
			"Alexandra Mays" ,
			"Earnestine Riggle" ,
			"Mildred Foster" ,
			"Rhoda Newman" ,
			"Leah Roche" ,
			"Adrian Ream" ,
			"Scot Ann" ,
			"Konnor David" ,
			"Abner Wilkinson" ,
			"Nichole Hutton" ,
			"Brennan Holts" ,
			"Gerard Armitage" ,
			"River Kimple" ,
			"Keely Graff" ,
			"Cecil Graham" ,
			"Herb Hoffhants" ,
			"Harmony Elsas" ,
			"Benson Moore" ,
			"Rickena Wood" ,
			"Vic Swarner" ,
			"William Kettlewell" ,
			"Rayner Fischer" ,
			"America Highlands" ,
			"Wilburn Lacon" ,
			"Lauraine Haines" ,
			"Anise Pawle" ,
			"Leroi Jenkins" ,
			"Haleigh Mcindoe" ,
			"Clem Berry" ,
			"Alberic Saltser" ,
			"Barbra Bynum" ,
			"Margaret Baxter" ,
			"Roberta Ropes" ,
			"Jolyon Baird" ,
			"Frazier Hook" ,
			"Stacy Lear" ,
			"Jakki Warner" ,
			"Kaden Tomey" ,
			"Gae Greenwood" ,
			"Roni Demuth" ,
			"Tina Southern" ,
			"Stew Blatenberger" ,
			"Linette Sanders" ,
			"Fabian Cady" ,
			"Trish Lalty" ,
			"Cathryn Reade" ,
			"Gabriel Cook" ,
			"Candida Lazzo" ,
			"Pamila Oppie" ,
			"Susan Jolce" ,
			"Idony Downing" ,
			"Madisyn Moon" ,
			"Alexander Marcotte" ,
			"Hedley Jones" ,
			"Jaye Osteen" ,
			"Chelle Mason" ,
			"Belle Pycroft" ,
			"Jonah Black" ,
			"Donny Blois" ,
			"Tyrone Fylbrigg" ,
			"Ellen Coldsmith" ,
			"Kristine Summy" ,
			"Mortimer Pirl" ,
			"Maximilian Flanders" ,
			"Aislin White" ,
			"Cassian Kunkle" ,
			"Gail Crawford" ,
			"Seamour Prescott" ,
			"Madelina Rosenstiehl" ,
			"Rue Munson" ,
			"Nessa Simmons" ,
			"Travers Swabey" ,
			"Josh Smothers" ,
			"Jessika Hatfield" ,
			"Katriona Hicks" ,
			"Sachie Tedrow" ,
			"Stirling Barkley" ,
			"Peta Mcclymonds" ,
			"Redd Jerome" ,
			"Trafford Thorley" ,
			"Ghislain Pershing" ,
			"Hopkin Baker" ,
			"Ashlie Wentzel" ,
			"Quin Bailey" ,
			"Sebastian Elizabeth" ,
			"Lolicia Nash" ,
			"Narelle Bennett" ,
			"Merilyn Alliman" ,
			"Driscoll Tilton" ,
			"Tillie Henley" ,
			"Noll Shaffer" ,
			"Velma Hunter" ,
			"Jasper Dugmore" ,
			"Laura Hil" ,
			"Jayne Pratt" ,
			"Emery Sadley" ,
			"Payton Alcocke" ,
			"Lorene Albright" ,
			"Lou Toyley" ,
			"Alea Wyatt" ,
			"Charla Cypret" ,
			"Ian Taggart" ,
			"Elspet Alington" ,
			"Marquis Ackerley" ,
			"Bryce Harding" ,
			"Sorrel Feufer" ,
			"Abraham Barnes" ,
			"Xena Kooser" ,
			"Jep Sutorius" ,
			"Jalen Dealtry" ,
			"Huey Chauvin" ,
			"Keefe Shafer" ,
			"Marje Stanfield" ,
			"Clive Hoenshell" ,
			"Amethyst Eliza" ,
			"Kegan Endsley" ,
			"Deitra Carter" ,
			"Alana Braun" ,
			"Judith Willcox" ,
			"Wil Wells" ,
			"Rusty Weidemann" ,
			"Janae Catlay" ,
			"Georgiana Gisiko" ,
			"Jaxon Beail" ,
			"Arielle Clarke" ,
			"Linnette Briggs" ,
			"Jonny Mull" ,
			"Derren Widaman" ,
			"Gord Trevithick" ,
			"Ulyssa Fonblanque" ,
			"Benita Gottwine" ,
			"Shane Levett" ,
			"Spencer Kalp" ,
			"Ralphie Catleay" ,
			"Ariella Swain" ,
			"Luanne Rifler" ,
			"Annie Bell" ,
			"Dianna Zoucks" ,
			"Claudius Hanford" ,
			"Geffrey Sullivan" ,
			"Brian Hatch" ,
			"Newton Hamilton" ,
			"Tranter Woodworth" ,
			"Pippa Ewing" ,
			"Delia Cowart" ,
			"Hiram Catherina" ,
			"Driskoll Craig" ,
			"Julianna Dugger" ,
			"Alissa Burch" ,
			"Drew Stoddard" ,
			"Howie Wain" ,
			"Bertha Moffat" ,
			"Lucas Carden" ,
			"Yasmina Elliott" ,
			"Ewart Ruch" ,
			"Shanika Munshower" ,
			"Peggie Goodman" ,
			"Marlyn Kellogg" ,
			"Radclyffe Tavoularis" ,
			"Eulalia Elless" ,
			"Chelsie Schmiel" ,
			"Jamaar Seidner" ,
			"Shannon Cavalet" ,
			"Abilene Osterweis" ,
			"Azure Bowman" ,
			"Karolyn Warren" ,
			"Hyram Bryant" ,
			"Ariadne Carpenter" ,
			"Cindra Weldi" ,
			"Jenelle Agnes" ,
			"Tibby Reiss" ,
			"Alberta Shaw" ,
			"Myron Walker" ,
			"Sheena Lowstetter" ,
			"Evan Beach" ,
			"Alvar Murray" ,
			"Mark Baker" ,
			"Diggory Focell" ,
			"Diana Wood" ,
			"Ora Diegel" ,
			"Kenyon Faust" ,
			"Pru Bard" ,
			"Lyndsea Richter" ,
			"Marylou Garratt" ,
			"Pam Williams" ,
			"Prince Woolery" ,
			"Kipling Lowry" ,
			"Marlene Blair" ,
			"Hettie Iseman" ,
			"Humphrey Cattley" ,
			"Edythe Wynter" ,
			"Farley Bender" ,
			"Sharyl Warren" ,
			"Meriel Simpson" ,
			"Cathy Zaun" ,
			"Lennox Nicholas" ,
			"Janina Gearhart" ,
			"Dinah Stocker" ,
			"Chrysanta Williams" ,
			"Lexi Marjorie" ,
			"Laurencia Wylie" ,
			"Nonie Porter" ,
			"Totty Beck" ,
			"Romey Eggbert" ,
			"Gina Reed" ,
			"Kristi Whishaw" ,
			"China Auman" ,
			"Flower Ledgerwood" ,
			"Tiara Ashbaugh" ,
			"Debbi Millard" ,
			"Alene Paul" ,
			"Almira Newbern" ,
			"Harold Bode" ,
			"Baptist Jesse" ,
			"Merton Werry" ,
			"Mora Whitehead" ,
			"Monroe Blackburn" ,
			"Gerald Baskett" ,
			"Jasmyn Ramsey" ,
			"Allan Newlove" ,
			"Wilfred Leonard" ,
			"Latonya Stahl" ,
			"Sue Schere" ,
			"Tracy Clark" ,
			"Felix Enderly" ,
			"Darell Hector" ,
			"Mckenna Wise" ,
			"Gerry Kifer" ,
			"Tamsin Goldvogel" ,
			"Cheyanne Greenawalt" ,
			"Ghislaine Wallick" ,
			"Brady Zadovsky" ,
			"Joby Canham" ,
			"Ormerod Glover" ,
			"Carson Dimsdale" ,
			"Lonny Wade" ,
			"Katy Johnson" ,
			"Keira Milne" ,
			"Gladys Mitchell" ,
			"Munro Ullman" ,
			"Rhett Knopsnider" ,
			"Trueman Sholl" ,
			"Felicia Bunten" ,
			"Branda Stough" ,
			"Joni Heckendora" ,
			"Graeme Anderson" ,
			"Ysabel Schofield" ,
			"Darla Hurst" ,
			"Virgil Veith" ,
			"Coretta Kimmons" ,
			"Jordyn Davis" ,
			"Chaz Hastings" ,
			"Clotilda Rowe" ,
			"Wayland Kistler" ,
			"Thurstan Mckendrick" ,
			"Eddy Lombardi" ,
			"Nellie Carbaugh" ,
			"Boniface Allshouse" ,
			"Jo Roadman" ,
			"Erle Vanleer" ,
			"Tamzen Day" ,
			"Ericka Dean" ,
			"Camryn Beard" ,
			"Ramsey Burns" ,
			"Erskine Otis" ,
			"Nevaeh Billimek" ,
			"Rosaline Thomas" ,
			"Cybill Harden" ,
			"Patsy Ewing" ,
			"Richie Higgens" ,
			"Leatrice Schmidt" ,
			"Benedict Paynter" ,
			"Bea Myers" ,
			"Salome Flickinger" ,
			"Bridget Laborde" ,
			"Rob Orbell" ,
			"Janice Kelley" ,
			"Ben Bryan" ,
			"Winfred Eiford" ,
			"Sammi Edwards" ,
			"Kaitlynn Reed" ,
			"Fred Parkinson" ,
			"Jerrard Campbell" ,
			"Laurine Duncan" ,
			"Kenton Yeskey" ,
			"Tatianna Napier" ,
			"Quincey Monroe" ,
			"Clover Brandenburg" ,
			"Lacey Morgan" ,
			"Oli Martin" ,
			"Shelagh Shotts" ,
			"Blythe Bishop" ,
			"Pauletta Haile" ,
			"Lynna Sherlock" ,
			"Lula Fea" ,
			"Corine Fuhrer" ,
			"Cade Owen" ,
			"Vernon Millhouse" ,
			"Latisha Heyman" ,
			"Stephen Wilks" ,
			"Ann Meyers" ,
			"Mariabella Lane" ,
			"Norm Keister" ,
			"Fraser Ratcliff" ,
			"Vere Osterweiss" ,
			"Jacquelyn Stiffey" ,
			"Jonelle Logue" ,
			"Jen Rogers" ,
			"Caileigh Holdeman" ,
			"Pete Mccullough" ,
			"Bruce Sommer" ,
			"Jethro Geddinge" ,
			"Jimmie Hildyard" ,
			"Wilton Hawker" ,
			"Lessie Joghs" ,
			"Andrea Wortman" ,
			"Pat Stern" ,
			"Sherman Swartzbaugh" ,
			"Lilith Brown" ,
			"Audley Sutton" ,
			"Kameron Chappel" ,
			"Yorick Tanner" ,
			"Audrey Buzzard" ,
			"Goddard Pratt" ,
			"Avelina Hallauer" ,
			"Jerrold Magor" ,
			"Ernesta Sanner" ,
			"Milburn Dunlap" ,
			"Joshua Gardner" ,
			"Jannine Stainforth" ,
			"Uland Newbiggin" ,
			"Sallie Rumbaugh" ,
			"Fern Wilkins" ,
			"Caleb Braham" ,
			"Deanne Conrad" ,
			"Nicola Schuck" ,
			"Billie Adcock" ,
			"Beauregard Sandys" ,
			"Ruby Shallenberger" ,
			"Trix Boyer" ,
			"Su Weeks" ,
			"Martie Wilson" ,
			"Amelia Roose" ,
			"Isidore Sanborn" ,
			"Eleanore Altman" ,
			"Allie Barr" ,
			"Marion Children" ,
			"Lela Flick" ,
			"Jaylen Fitzgerald" ,
			"Isolde Briner" ,
			"Tylor Jelliman" ,
			"Ron Close" ,
			"Elly Little" ,
			"Bart Sulyard" ,
			"Brandon Cason" ,
			"Peace Gadow" ,
			"Mort Coughenour" ,
			"Jerri Ashmore" ,
			"Edith Leichter" ,
			"Flick Burney" ,
			"Amyas West" ,
			"Rae Leech" ,
			"Algar Mixey" ,
			"Kimberleigh Swink" ,
			"Steven Branson" ,
			"Landon Draudy" ,
			"Elfreda Wallace" ,
			"Sherley Sloan" ,
			"Prosper Hynes" ,
			"Constant Surrency" ,
			"Fulke Cowper" ,
			"Randi Mckinnon" ,
			"Howard Tue" ,
			"Zilla Greif" ,
			"Sawyer Nehling" ,
			"Read Oneal" ,
			"Curtis Fisher" ,
			"Fleuretta Whiteman" ,
			"Wanda Langston" ,
			"Haywood Mcfall" ,
			"Melisa Knisely" ,
			"Dione Laurenzi" ,
			"Marius Archibald" ,
			"Jareth Holtzer" ,
			"Jayde Rahl" ,
			"Ella Butt" ,
			"Elfrida James" ,
			"Grosvenor Baumgartner" ,
			"Babs Akers" ,
			"Floyd Aft" ,
			"Neely Johann" ,
			"Aria Best" ,
			"Shania Isaman" ,
			"Ross Hirleman" ,
			"Camden Ward" ,
			"Faithe Dimeling" ,
			"Angelia Tomlinson" ,
			"Guiscard Beals" ,
			"Adela Hill" ,
			"Darin Shupe" ,
			"Lloyd Weldy" ,
			"Henrietta Sybilla" ,
			"Myrtie Watkins" ,
			"Joseph Eva" ,
			"Hope Dale" ,
			"Jere Mingle" ,
			"Maitland Lotherington" ,
			"Arthur Bashline" ,
			"Nicholas Strickland" ,
			"Sarah Fair" ,
			"Storm Mckee" ,
			"Meagan Bloise" ,
			"Lenore Seelig" ,
			"Marsha Swift" ,
			"Jean Stroh" ,
			"Karrie Philbrick" ,
			"Jamar Butler" ,
			"Roderic Mayers" ,
			"Judd Mcelroy" ,
			"Michael Watson" ,
			"Berniece Loewentsein" ,
			"Magnus Bauerle" ,
			"Vin Buehler" ,
			"Jenn Earl" ,
			"Bryan Overstreet" ,
			"Orval Trovato" ,
			"Daniella Minnie" ,
			"Dion Wegley" ,
			"Roly Bowchiew" ,
			"Phyllida Reighner" ,
			"Francene Unk" ,
			"Kizzie Queer" ,
			"Kodey Cox" ,
			"Fawn Gongaware" ,
			"Wendy Hoover" ,
			"Denholm Peters" ,
			"Giselle Toulmin" ,
			"Delilah Mcmullen" ,
			"Lally Joyce" ,
			"Griffin Jardine" ,
			"Eden Kepple" ,
			"Creighton Rhinehart" ,
			"Malina Dunkle" ,
			"Caryl Burkett" ,
			"Napier Powell" ,
			"Martha Frankenberger" ,
			"Saffie Bratton" ,
			"Cadence Dickson" ,
			"Shawnee Cherry" ,
			"Tamra Lowe" ,
			"Lance Stall" ,
			"Ravenna Gaskins" ,
			"Charity Hobbs" ,
			"Trina Eastwood" ,
			"Raeburn Overholt" ,
			"Ria Sachse" ,
			"Rowina Spring" ,
			"Washington Warrick" ,
			"Lalage Baer" ,
			"Roselyn Houser" ,
			"Ebba Marriman" ,
			"Kendra Mench" ,
			"Evalyn Fisher" ,
			"Reuben Mackendrick" ,
			"Taylor Eisenmann" ,
			"Oberon Throckmorton" ,
			"Nick Doverspike" ,
			"King Priebe" ,
			"Corie Noton" ,
			"Jenni Schrader" ,
			"Mayra Dryfus" ,
			"Reanna Moberly" ,
			"Toni Porter" ,
			"Otis Zundel" ,
			"Eleanor Wildman" ,
			"Jolene Mcdonald" ,
			"Lucile Fields" ,
			"Delmar Moonshower" ,
			"Lallie Howe" ,
			"Jonie Sauter" ,
			"Greta Caesar" ,
			"Zacharias Moulton" ,
			"Candice Richardson" ,
			"Serina Raub" ,
			"Ilene Jyllian" ,
			"Darius Shirey" ,
			"Nikolas Rummel" ,
			"Lancelot Howard" ,
			"Nelly Hasely" ,
			"Rosy Kuster" ,
			"Gwenda Byers" ,
			"Jera Potter" ,
			"Eppie Hahn" ,
			"Aleesha Kemerer" ,
			"Dave Groah" ,
			"Diane Nickolson" ,
			"Dorothea Sell" ,
			"Rica Koster" ,
			"Melitta Kiefer" ,
			"Placid Stange" ,
			"Lindon Stroble" ,
			"Dolores Fulton" ,
			"Angel Hair" ,
			"Danette Keener" ,
			"Beulah Roberts" ,
			"Larry Knapenberger" ,
			"Jonty Cass" ,
			"Mordikai Mildred" ,
			"Addie Kight" ,
			"Manley Walker" ,
			"Lovel Baum" ,
			"Guinevere Lester" ,
			"Peppi Chase" ,
			"Zubin Camp" ,
			"Mallory Erskine" ,
			"Walton Barth" ,
			"Crispin Jewell" ,
			"Maybelle Evans" ,
			"Divina Foster" ,
			"Brad Hatcher" ,
			"Petula Casteel" ,
			"Crystal Saylor" ,
			"Selby Morland" ,
			"Bonnie Steele" ,
			"Eugenia Shea" ,
			"Eudora Winton" ,
			"Bridgette Chapman" ,
			"Alger Hardie" ,
			"Coty Schneider" ,
			"Harrison White" ,
			"Stewart Knapp" ,
			"Tracee Henry" ,
			"Ada Putnam" ,
			"Maynard Armstrong" ,
			"Paise Gleper" ,
			"Baylee Carmichael" ,
			"Justy Alice" ,
			"Thorburn Hardy" ,
			"Diann Marshall" ,
			"Lottie Holdsworth" ,
			"Cymbeline Sayre" ,
			"Lacy Caldwell" ,
			"Lyndi Miller" ,
			"Sheridan Bullard" ,
			"Kaylee Milliron" ,
			"Amber Stafford" ,
			"Brendon Ulery" ,
			"Riley Bicknell" ,
			"Beatrix Brooks" ,
			"Bobbi Pfeifer" ,
			"Walker Rowley" ,
			"Dona Judge" ,
			"Carey Mens" ,
			"Chad Woodward" ,
			"Manfred Rader" ,
			"Anson Taylor" ,
			"Jayme Cribbs" ,
			"Petrina Moore" ,
			"Manuel Muller" ,
			"Ellie Hindman" ,
			"Jillie Osterwise" ,
			"Gareth Painter" ,
			"Piety Benford" ,
			"Lyric Mary" ,
			"Yolanda Busk" ,
			"Larkin Mitchell" ,
			"Jerold Ryals" ,
			"Wilmot Baughman" ,
			"Colleen Saline" ,
			"Jewell Hunt" ,
			"Cambria Lineman" ,
			"Kisha Pittman" ,
			"Richard Reichard" ,
			"Annmarie Wilkerson" ,
			"Robertina Hice" ,
			"Judah Losey" ,
			"Darwin Robinson" ,
			"Hillary Easter" ,
			"Lorayne Koepple" ,
			"Gillian Thomlinson" ,
			"Debra Reese" ,
			"Wilfreda Yonkie" ,
			"Aida Willey" ,
			"Rozanne Filby" ,
			"Ruth Shick" ,
			"Rebekah Rosensteel" ,
			"Kizzy Emrick" ,
			"Tiphanie Adams" ,
			"Kimberley Lauffer" ,
			"Fletcher Polson" ,
			"Marcie Gronko" ,
			"Tresha Bousum" ,
			"Alannis Stewart" ,
			"Irene Brindle" ,
			"Bonita Blessig" ,
			"Marilyn Barnes" ,
			"Saffron Herndon" ,
			"Isaac Gregory" ,
			"Nan Ring" ,
			"Kolour Bould" ,
			"Sharron Weisgarber" ,
			"Jaqueline Sealis" ,
			"Tiffany Fleming" ,
			"Percy Cowher" ,
			"Blake Dull" ,
			"Elliot Christner" ,
			"Thom Bash" ,
			"Joachim Maugham" ,
			"Theresa Robertson" ,
			"Sarra Rodacker" ,
			"Barret Klockman" ,
			"Lesley Johns" ,
			"Dee Countryman" ,
			"Louise Drennan" ,
			"Nevada Armstrong" ,
			"Charmian Drabble" ,
			"Cornelia Eisaman" ,
			"Pris Fuchs" ,
			"Cymone Perkins" ,
			"Carmel Huston" ,
			"Ivory Guest" ,
			"Davina Eisenman"]; 


function empty_the_collections(db) {
    var all_collections = db.getCollectionNames(); 
    for (var i=0; i < all_collections.length; i++) { 
	var this_collection = all_collections[i];
	if (this_collection != 'system.indexes') {
	    print("we will now empty this collection: " + this_collection); 
	    db[this_collection].remove(); 
	}
    }
}

function show_counts_of_the_collections(db) {
    var all_collections = db.getCollectionNames(); 
    for (var i=0; i < all_collections.length; i++) { 
	print("how many records are in this collection: " + all_collections[i]); 
	var this_collection = all_collections[i];
	print(db[this_collection].count()); 
    }
}

function get_a_new_fake_name() {
    // a hack of a function, quick and dirty to get some names
    var fake_name_1 = "Mike" + Math.floor((Math.random() * 1000));
    var fake_name_2 = "Angela" + Math.floor((Math.random() * 1000));
    var fake_name_3 = "Ashton" + Math.floor((Math.random() * 1000));
    var fake_name_4 = "Gregory" + Math.floor((Math.random() * 1000));

    var random_index_to_find_a_fake_user = Math.floor((Math.random() * 1000));
    if (array_of_fake_names.length > random_index_to_find_a_fake_user) {
	var fake_name_1 = array_of_fake_names[random_index_to_find_a_fake_user];	
    }
    var random_index_to_find_a_fake_user = Math.floor((Math.random() * 1000));
    if (array_of_fake_names.length > random_index_to_find_a_fake_user) {
	var fake_name_2 = array_of_fake_names[random_index_to_find_a_fake_user];	
    }
    var random_index_to_find_a_fake_user = Math.floor((Math.random() * 1000));
    if (array_of_fake_names.length > random_index_to_find_a_fake_user) {
	var fake_name_3 = array_of_fake_names[random_index_to_find_a_fake_user];	
    }
    var random_index_to_find_a_fake_user = Math.floor((Math.random() * 1000));
    if (array_of_fake_names.length > random_index_to_find_a_fake_user) {
	var fake_name_4 = array_of_fake_names[random_index_to_find_a_fake_user];	
    }
    var array_of_4_names = [fake_name_1, fake_name_2, fake_name_3, fake_name_4];  

    var mixed_name = "";
    for (var x=0; x < array_of_4_names.length; x++) {
	var this_fake_name = array_of_4_names[x];
	var array_of_first_and_last = this_fake_name.split(" "); 
	if (Math.floor((Math.random() * 10)) > 4) {
	    mixed_name = mixed_name + " " + array_of_first_and_last[0];
	} else {
	    mixed_name = mixed_name + " " + array_of_first_and_last[1];
	}
	if (x == 2) {
	    mixed_name = mixed_name + "-";
	}
    }
    return mixed_name; 
}

function add_first_and_last_names_to_user_accounts(db) {
    var users_without_names = db['User'].find({ "lastname" : null });
    print("We will adjust these user accounts: " + users_without_names.length());
    print(users_without_names); 
    for (var i=0; i < users_without_names.length(); i++) { 
	var this_user = users_without_names[i];
	var user_id = this_user["_id"];
	var mixed_name = get_a_new_fake_name(); 
	var array_of_split_name = mixed_name.split("-"); 
	var firstname = array_of_split_name[0];
	var lastname = array_of_split_name[1];
	this_user["firstname"] = firstname; 
	this_user["lastname"] = lastname;
	this_user["origin_why"] = "add_first_and_last_names_to_user_accounts";
	print("Now updating the user with the id of: " + firstname + " " + lastname); 
	print(user_id); 
	db.User.update( { "_id" : user_id }, this_user); 
    }
}

function unset_non_standard_name_fields(db){
    var users_with_non_standard_name_fields = db.User.find({"first_name" : {$exists : 1}});
    for (var i=0; i < users_with_non_standard_name_fields.length(); i++) { 
	var this_user = users_with_non_standard_name_fields[i];
	var user_id = this_user["_id"];
	db.User.update( { "_id" : user_id }, { $unset : { "last_name" : "", "first_name" : "" }  }); 
    } 
}

function remove_imported_and_fake_data(db) {
    var all_collections = db.getCollectionNames(); 
    for (var i=0; i < all_collections.length; i++) { 
	var this_collection = all_collections[i];
	if (this_collection != 'system.indexes') {
	    print(this_collection); 
	    print("we will now remove 'this_document_was_imported_from':'opensis' this collection: " + this_collection); 
	    print(db[this_collection].remove({'this_document_was_imported_from':'opensis'})); 
	    print("we will now remove 'this_document_was_imported_from':'moodle' this collection: " + this_collection); 
	    print(db[this_collection].remove({'this_document_was_imported_from':'moodle'})); 
	    print("we will now remove 'item-type' : 'last_imported_moodle_ids' from this collection: " + this_collection); 
	    print(db[this_collection].remove({ 'item-type' : 'last_imported_moodle_ids'})); 
	    print("we will now remove 'item-type' : 'last_imported_opensis_ids' from this collection: " + this_collection); 
	    print(db[this_collection].remove({ 'item-type' : 'last_imported_opensis_ids'})); 
	    print("we will now remove 'origin':'opensis' this collection: " + this_collection); 
	    print(db[this_collection].remove({'origin':'opensis'})); 
	    print("we will now remove 'origin':'moodle' this collection: " + this_collection); 
	    print(db[this_collection].remove({'origin':'moodle'})); 
	    print("we will now remove 'origin':'fake-from-loira' this collection: " + this_collection); 
	    print(db[this_collection].remove({'origin':'fake-from-loira'})); 
	}
    }
}

// 2014-07-22 - taken from here
// http://stackoverflow.com/questions/264430/how-can-i-get-a-list-of-the-differences-between-two-javascript-object-graphs
function findDifferences(objectA, objectB) {
    var propertyChanges = [];
    var objectGraphPath = ["this"];
    (function(a, b) {
	if(a.constructor == Array) {
            // BIG assumptions here: That both arrays are same length, that
            // the members of those arrays are _essentially_ the same, and 
            // that those array members are in the same order...
            for(var i = 0; i < a.length; i++) {
		objectGraphPath.push("[" + i.toString() + "]");
		arguments.callee(a[i], b[i]);
		objectGraphPath.pop();
            }
	} else if(a.constructor == Object || (a.constructor != Number && 
					      a.constructor != String && a.constructor != Date && 
					      a.constructor != RegExp && a.constructor != Function &&
					      a.constructor != Boolean)) {
            // we can safely assume that the objects have the 
            // same property lists, else why compare them?
            for(var property in a) {
		objectGraphPath.push(("." + property));
		if(a[property].constructor != Function) {
		    arguments.callee(a[property], b[property]);
		}
		objectGraphPath.pop();
            }
	} else if(a.constructor != Function) { // filter out functions
            if(a != b) {
		propertyChanges.push({ "Property": objectGraphPath.join(""), "ObjectA": a, "ObjectB": b });
            }
	}
    })(objectA, objectB);
    return propertyChanges;
}

function find_items_in_second_array_that_are_not_in_first_array (a1, a2) {
    var diff=[];

    for (var i=0; i< a2.length; i++) {
	var next_item = a2[i];
	var does_this_item_exist_in_the_first_array = a1.indexOf(next_item); 
	print(" for " + next_item + " we got the matching result: " + does_this_item_exist_in_the_first_array); 
	if (does_this_item_exist_in_the_first_array == -1) {
	    diff.push(a2[i]);
	}
    }
    return diff;
}

function find_differences_in_this_collections_documents (collection_name) {
    // 2014-07-22 - we use this function mostly to see the difference between a
    // "User" imported from OpenSIS and a "User" imported from Moodle.
    // I am being lazy right now, so I will only compare top level keys. 
    // Later I will make this function an in-depth search.
    // Added skip(2) to avoid the 2 irregular documents that the importer inserts.
    var cursor = db[collection_name].find().skip(2);
    // start with any document
    var intitial_document = cursor[0];
    var array_of_initial_keys = []; 
    for (var key in intitial_document) { array_of_initial_keys.push(key); }
    // we don't want all (of the same) keys from 500 documents that are different from 
    //  the first document, so we will collect changes as we find them. 
    var array_of_keys_to_not_match = array_of_initial_keys.slice(0); 
    var array_of_different_keys = [];

    print("The number of items found in this collection: " + cursor.length());

    for (var i=1; i < cursor.length(); i++) {
	var next_document = cursor[i];
	var array_of_next_document_keys = [];
	for (var key in next_document) { array_of_next_document_keys.push(key); }
	var keys_that_are_different = find_items_in_second_array_that_are_not_in_first_array(array_of_keys_to_not_match, array_of_next_document_keys);
	for (var w=0; w < keys_that_are_different.length; w++) {
	    // we don't want all (of the same) keys from 500 documents that are different from 
	    //  the first document, so we will collect changes as we find them. 
	    array_of_keys_to_not_match.push(keys_that_are_different[w]);
	    array_of_different_keys.push(keys_that_are_different[w]); 
	}
    }

    print("These are the initial keys:");
    printjson(array_of_initial_keys);
    print("These other keys were found:");
    printjson(array_of_different_keys); 
}



